name: CI
on: [push]
jobs:
  build-on-unix:
    strategy:
      matrix:
        java: [11]
        nodejs-version: [12]
        python-version: [3.8]
        gradle-version: [6.2]
        maven-version: [3.6.3]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
#      - name: Set up NodeJS ${{ matrix.nodejs-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.nodejs-version }}
#      - name: Install required npm packages globally
#        run: npm install -g wait-port
#      - name: Cache npm
#        uses: actions/cache@v1
#        with:
#          path: ~/.npm
#          key: ${{ matrix.nodejs-version }}-${{ matrix.os }}-npm-cache
#          restore-keys: |
#            ${{ matrix.nodejs-version }}-${{ matrix.os }}-npm-cache-
#
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install / upgrade pip
#        run: python -m pip install --upgrade pip setuptools
#      - name: Install HTTPie
#        run: pip install --upgrade httpie
      - name: Git clone
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
#      - name: Set up maven
#        uses: stCarolas/setup-maven@v3
#        with:
#          maven-version: ${{ matrix.maven-version }}
#      - name: Maven build
#        run: cd $GITHUB_WORKSPACE && mvn
#      - name: Run
#        run: |
#          java -jar $GITHUB_WORKSPACE/target/*-all.jar
#      - name: Cache maven
#        uses: actions/cache@v1
#        with:
#          path: ~/.m2/repository
#          key: ${{ matrix.maven-version }}-${{ matrix.os }}-maven-cache
#          restore-keys: |
#            ${{ matrix.maven-version }}-${{ matrix.os }}-maven-cache-
      - name: Build gradle app
        uses: eskatos/gradle-command-action@v1
        env:
          CI: true
        with:
          #build-root-directory: .
          gradle-version: ${{ matrix.gradle-version }}
          arguments: clean build -S
      - name: Test gradle app
        shell: bash
        run: java -Dfile.encoding="UTF-8" -jar $GITHUB_WORKSPACE/build/libs/*-all.jar
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ matrix.gradle-version }}-${{ matrix.os }}-gradle-cache
          restore-keys: |
            ${{ matrix.gradle-version }}-${{ matrix.os }}-gradle-cache-
  build-on-windows:
    strategy:
      matrix:
        java: [11]
        nodejs-version: [12]
        python-version: [3.8]
        gradle-version: [6.2]
        maven-version: [3.6.3]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
#      - name: Set up NodeJS ${{ matrix.nodejs-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.nodejs-version }}
#      - name: Install required npm packages globally
#        run: npm install -g wait-port
#      - name: Cache npm
#        uses: actions/cache@v1
#        with:
#          path: ~/.npm
#          key: java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-npm-
#          restore-keys: |
#            java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-npm-
#
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install / upgrade pip
#        run: python -m pip install --upgrade pip setuptools
#      - name: Install HTTPie
#        run: pip install --upgrade httpie
      - name: Git clone
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
#      - name: Set up maven
#        uses: stCarolas/setup-maven@v3
#        with:
#          maven-version: ${{ matrix.maven-version }}
#      - name: Build maven app
#        shell: cmd
#        run: cd %GITHUB_WORKSPACE% & mvn -Dfile.encoding="UTF-8"
#      - name: Test maven app
#        shell: cmd
#        run: |
#          @chcp 65001>nul
#          echo "Do not generate with openssl on Windows! It's doesn't work!"
#          java -Dfile.encoding="UTF-8" -jar %GITHUB_WORKSPACE%\target\kotlin-map-db-1.0.0-SNAPSHOT-all.jar
#      - name: Cache maven
#        uses: actions/cache@v1
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
      - name: Build gradle app
        uses: eskatos/gradle-command-action@v1
        env:
          CI: true
        with:
          build-root-directory: .
          gradle-version: ${{ matrix.gradle-version }}
          arguments: -S
      - name: Test gradle app
        shell: cmd
        run: |
          @chcp 65001>nul
          java -Dfile.encoding="UTF-8" -jar %GITHUB_WORKSPACE%\build\libs\kotlin-map-db-1.0.0-SNAPSHOT-all.jar
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-gradle-${{ hashFiles('**/.gradle/**') }}
          restore-keys: |
            java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-gradle-
