name: CI
on: [push]
jobs:
  build-on-unix:
    strategy:
      matrix:
        java: [8,11]
        gradle-version: [6.3]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} java ${{ matrix.java }}
    steps:
      - name: Git clone
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ matrix.gradle-version }}-${{ matrix.os }}-gradle-cache
          restore-keys: |
            ${{ matrix.gradle-version }}-${{ matrix.os }}-gradle-cache-
      - name: Build gradle app
        uses: eskatos/gradle-command-action@v1
        env:
          CI: true
        with:
          #build-root-directory: .
          gradle-version: ${{ matrix.gradle-version }}
          arguments: clean build -S -Dsleep=35
      - name: Test gradle app
        shell: bash
        run: java -Dfile.encoding="UTF-8" -jar $GITHUB_WORKSPACE/build/libs/*-all.jar
  build-on-windows:
    strategy:
      matrix:
        java: [11,1.8]
        nodejs-version: [12]
        gradle-version: [6.3]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} java ${{ matrix.java }}
    steps:
      - name: Git clone
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-gradle-
      - name: Build gradle app
        uses: eskatos/gradle-command-action@v1
        env:
          CI: true
        with:
          build-root-directory: .
          gradle-version: ${{ matrix.gradle-version }}
          arguments: -S -Dsleep=25
      - name: Test gradle app
        shell: cmd
        run: |
          @chcp 65001>nul
          java -Dfile.encoding="UTF-8" -jar %GITHUB_WORKSPACE%\build\libs\kotlin-map-db-1.0.0-SNAPSHOT-all.jar
